### PR TITLE
Support Pipenv

### PR DESCRIPTION
**Pull request by petrhosek**
Pipenv combines Pipfile, pip, and virtualenv into one single command. This allows specifying only the direct dependencies, and relying on Pipenv for generating the lockfile and install packages.

### CODE REVIEW

**Comment by petrhosek** [comment]
I'm currently seeing the following error when running `run_tests.sh` inside the container:
```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
This still needs to be addressed.

**Comment by boomanaiden154** [comment]
This looks a lot better than what we're doing currently and is definitely a much better option than what I had proposed in #128. I'm assuming the move from `tf-nightly` to `tensorflow==2.11.0rc1` is because the changes that we were depending upon in nightly before have now made the 2.11.0 branch?

There should probably be some minor follow ups on this (ie updating documentation and maybe some documentation on updating dependencies), but I can take care of those later and we can get this in so that you can get unblocked.

**Comment by boomanaiden154** [comment]
> I'm currently seeing the following error when running `run_tests.sh` inside the container:
> 
> ```
> DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
> ```
> 
> This still needs to be addressed.

The current protocol for deprecation warnings in downstream dependencies is to open an Issue documenting the warning and then add a line in `pytest.ini` to ignore it.

**Comment by mtrofin** [comment]
Can you please update the CI to use this, too - and then can we remove the requirements.txt family of files?

**Comment by petrhosek** [comment]
> Can you please update the CI to use this, too - and then can we remove the requirements.txt family of files?

Where is the CI configuration?

**Comment by boomanaiden154** [comment]
> Where is the CI configuration?

`./github/workflows/main.yml`

**Comment by boomanaiden154** [comment]
#189 finished this transition since Petr is OOO for the rest of the year.

**Pull request closed without merging**
