### PR TITLE
Update demo link

### LINKED ISSUE #181: Demo link not working
The demo link provided in the README.md is not working.

### PR DESCRIPTION
**Pull request by LakshmanKishore**
Should fix #181 

Demo link present in the Docs section of README.md was not updated in #182

### CODE REVIEW

**Comment by yundiqian** [comment]
Hi Lakshman, thanks for submitting this pr for the fix. Can you sign the CLA that is required by contributing too Google open source project? (see the above google-cla bot comment)

**Comment by LakshmanKishore** [comment]
Yes, I have signed the CLA and rescanned the pull request.
After the message appeared, I instantly signed the CLA. Will the Google-cla comment disappears after signing?

**Comment by yundiqian** [comment]
cool! i see that, I will merge your change after the checks pass

**Comment by LakshmanKishore** [comment]
Yes, Thank you!

**Pull request merged**
